import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';

interface MermaidDiagramProps {
  chart: string;
}

const MermaidDiagram: React.FC<MermaidDiagramProps> = ({ chart }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // Check if dark mode is active in the document
    const isDark = document.documentElement.classList.contains('dark');
    
    // Re-initialize mermaid with appropriate theme
    mermaid.initialize({
      startOnLoad: false,
      theme: isDark ? 'dark' : 'default',
      securityLevel: 'loose',
      fontFamily: 'Inter, sans-serif',
    });

    let isMounted = true;

    const renderChart = async () => {
      if (!chart) return;
      
      try {
        const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`;
        
        // Clean up the input string
        let cleanChart = chart.trim();
        // Sometimes the AI output includes "mermaid" at the start of the block content
        if (cleanChart.toLowerCase().startsWith('mermaid')) {
          cleanChart = cleanChart.substring(7).trim();
        }

        // SANITIZATION: Fix common subgraph syntax errors generated by LLMs
        // Example problem: subgraph Class Definition (spaces illegal)
        // Fix: subgraph ClassDefinition ["Class Definition"]
        const lines = cleanChart.split('\n');
        const fixedLines = lines.map(line => {
          const trimmed = line.trim();
          if (trimmed.startsWith('subgraph ')) {
            const rest = trimmed.substring(9).trim();
            
            // Regex to check if it matches valid pattern: ID or ID ["Title"] or ID [Title]
            // Valid IDs are strictly alphanumeric + underscore.
            // If it doesn't start with a valid ID followed by end-of-string or [, then we fix it.
            const validIdMatch = rest.match(/^([a-zA-Z0-9_]+)(\s*\[.*?\])?$/);
            
            if (!validIdMatch) {
                // It's likely "subgraph Some Title" or "subgraph func()"
                // Generate safe ID (remove non-alphanumeric)
                const safeId = rest.replace(/[^a-zA-Z0-9]/g, '') || `sg${Math.random().toString(36).substr(2, 5)}`;
                
                // Return reformatted line with original indentation
                const indent = line.substring(0, line.indexOf('subgraph'));
                return `${indent}subgraph ${safeId} ["${rest}"]`;
            }
          }
          return line;
        });
        cleanChart = fixedLines.join('\n');

        // Mermaid expects valid syntax. The model might sometimes output slightly broken syntax.
        // We attempt to render it.
        const { svg: renderedSvg } = await mermaid.render(id, cleanChart);
        
        if (isMounted) {
          setSvg(renderedSvg);
          setError(null);
        }
      } catch (err) {
        console.error("Mermaid render error:", err);
        if (isMounted) {
          setError("Failed to render diagram. The AI generated invalid syntax.");
        }
      }
    };

    renderChart();

    return () => {
      isMounted = false;
    };
  }, [chart]);

  if (error) {
    return (
      <div className="p-4 bg-red-50 dark:bg-red-900/20 border border-red-100 dark:border-red-900/30 rounded text-red-600 dark:text-red-400 text-sm font-mono whitespace-pre-wrap">
        <p className="font-bold mb-2">Diagram Error:</p>
        {error}
        <div className="mt-2 text-xs text-slate-500 dark:text-slate-400">Raw Source:</div>
        <div className="mt-1 text-xs opacity-75">{chart}</div>
      </div>
    );
  }

  return (
    <div 
      className="mermaid-container my-6 p-4 bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm overflow-x-auto flex justify-center"
      ref={containerRef}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
};

export default MermaidDiagram;